services:
  db:
    image: postgres:18-alpine3.23
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${DB_USERNAME}']
      interval: 5s
      retries: 5

    ports:
      - '${DB_PORT}:5432'

volumes:
  db_data:
